### ISSUE TITLE
Display a list of emojis when the input is empty

### ISSUE THREAD

**Issue by pokk** [devnoname120/alfred-emoji-picker#1]
That's an awesome project.

Just would like to know how to show all emojis?

**Comment by devnoname120** [comment]
Thanks!

----------------

This is currently not possible. The initial list is empty on purpose so that the Alfred prompt can be available right away.

Alternatively you could look for a specific category by typing e.g. `smiley` or `face`.

I could display all emojis if the prompt only contains a space but I'm not convinced it's worth adding this feature. What do you need it for?

**Comment by devnoname120** [comment]
Alfred 5 has support for the `skipknowledge` field:

> The Script Filter object has a new `skipknowledge` boolean field in the JSON, preventing Alfred from sorting your outputted results when using UIDs for reselection

If I understand correctly, this feature would enable us to display the most frequently-used emojis when nothing is typed, otherwise use our custom ordering/sorting.

I'm not sure that I want to drop Alfred 4 support just for that, I'm not sure yet.

**Comment by pokk** [comment]
@devnoname120 
Thank you so much for the quick reply.

I am using Alfred 5, will take a look that how to use that `skipknowledge` field.

> I could display all emojis if the prompt only contains a space but I'm not convinced it's worth adding this feature. What do you need it for?

I am a user of https://github.com/jsumners/alfred-emoji, I saw your comment on that repo. So I tried your workflow, and it's pretty good.
Just be used to using kinda usage, just wondering if it is possible. 👍

**Comment by pokk** [comment]
@devnoname120 
I am so sorry for asking this dumb question, if it is possible, could you please share how to add `skipknowledge`? Just couldn't find how to do that. 🙏

**Comment by devnoname120** [comment]
@pokk You need to:
- Modify the workflow in Alfred to call the script even if the argument is 0
- Modify the `search()` function so that it returns all the emojis if the `query` is empty.
- Modify https://github.com/deanishe/awgo to add  `"skipknowledge": true` to the top level JSON object that is returned.

**Comment by veged** [comment]
it would be helpful to have something like «Favorites» list, which could be shown on empty query

**Comment by devnoname120** [comment]
> it would be helpful to have something like «Favorites» list, which could be shown on empty query

I plan to display the most frequently used emojis if the input is empty. Do you think that it would cover your use case?

If I display favorites then I can't display the most frequently used emojis at all, which I think would be a step down feature-wise.

**Comment by veged** [comment]
> > it would be helpful to have something like «Favorites» list, which could be shown on empty query
> 
> I plan to display the most frequently used emojis if the input is empty. Do you think that it would cover your use case?
> 
> If I display favorites then I can't display the most frequently used emojis at all, which I think would be a step down feature-wise.

should be fine enough 👌 for now I'm just done quick fix:
```sh
query=$*

# This improves startup time by not calling the executable when no argument is provided
# This helps make sure that invoking the hotkey shows the input right away and such catch pressed keys right away

if [[ -z "$query" ]]; then
	cat ~/.config/alfred-favorites-emojis.json
else
	./alfred-emoji-picker "$query"
fi
```

**Comment by devnoname120** [comment]
@veged Thanks for your input! I'll need to make sure that startup time isn't worsened because otherwise the emoji picker can miss the first key input if the user types immediately after pressing the hotkey for opening the emoji picker.
